name: Bionic x86 Clang Release

on:
  push:
    branches: [tbb_2019_custom]
  pull_request:
    branches: [tbb_2019_custom]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: install bionic dependencies
        run: sudo ./.vscode/install_bionic_dependencies.sh
      - name: build bionic x86 clang release
        run: ./.vscode/build_bionic_x86_clang_release.sh
