name: OSX Debug

on:
  push:
    branches: [tbb_2019_custom]
  pull_request:
    branches: [tbb_2019_custom]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: build osx debug
        run: ./.vscode/build_mach_osx_debug.sh
