name: IOS Release

on:
  push:
    branches: [tbb_2019_custom]
  pull_request:
    branches: [tbb_2019_custom]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: build ios release
        run: ./.vscode/build_mach_ios_release.sh
