name: Ubuntu 16.04 LTS x86 Clang Release

on:
  push:
    branches: [tbb_2019_custom]
  pull_request:
    branches: [tbb_2019_custom]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: install ubuntu dependencies x86
        run: sudo ./.vscode/install_ubuntu_dependencies_x86.sh
      - name: build ubuntu x86 clang release
        run: ./.vscode/build_x86_clang_release.sh
